### ISSUE TITLE
Is there a time limit for using Ultimine once the Mining Certificate is open?

### ISSUE THREAD

**Issue by JasdanVM** [ixDarkLorD/UltimineAddition#3]
If not, that would be a great addition.

**Comment by ixDarkLorD** [comment]
I'm sorry for taking too much time to respond to the ticket.
Good news! I have created a way through Potions. Check the mod's new update.

**Comment by ixDarkLorD** [comment]
I don't think it will suit the mod's current mechanics.
There are 2 reasons for that:
- I already created a way to obtain the Ultimine ability for a limited time through brewing potions using the Mining Skill Card.
- The crafting of the Miner Certificate item is already tough to do! Because of the cards and the challenges. If I've made it so that it has durability and is being consumed over time, It will be a headache for players to craft it again.

But don't worry! I will consider the idea and find a solution for that if it is possible. ❤️🙏
